#!/usr/bin/env python3
# -*- encoding: utf-8 -*-
"""
Concourse in resource
"""
import sys

import os.path

from resource import Resource

if __name__ == '__main__':
    r = Resource()
    try:
        rcode = r.run(os.path.basename(__file__))
    except Exception as e:
        sys.stderr.write("ERROR: " + str(e) + "\n")
        sys.exit(1)
    sys.exit(rcode)
