#!/usr/bin/env python3
# -*- encoding: utf-8 -*-
"""
Concourse out resource
"""
import sys

import os.path
from ansible.utils.display import Display

display = Display()

from ansible_playbook import AnsiblePlaybook

if __name__ == '__main__':
    r = AnsiblePlaybook()
    try:
        rcode = r.run(os.path.basename(__file__))
    except Exception as e:
        sys.stderr.write("ERROR: " + str(e) + "\n")
        sys.exit(1)
    sys.exit(rcode)
